
nohup python main.py --phi_design "low" --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 1.0 --objective_option "weighted_average" --trainer_lr 1e-2 --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker_lr 1e-4 --train_attacker_projection_lr 1e-3 --train_attacker_projection_time_limit 5.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 1 --affix "low_cbf_reg_weight_1_seed_1" --gpu 0 &> low_cbf_reg_weight_1_seed_1.out &

nohup python main.py --phi_design "low" --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 1.0 --objective_option "weighted_average" --trainer_lr 1e-2 --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker_lr 1e-4 --train_attacker_projection_lr 1e-3 --train_attacker_projection_time_limit 5.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 2 --affix "low_cbf_reg_weight_1_seed_2" --gpu 0 &> low_cbf_reg_weight_1_seed_2.out &

nohup python main.py --phi_design "low" --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 1.0 --objective_option "weighted_average" --trainer_lr 1e-2 --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker_lr 1e-4 --train_attacker_projection_lr 1e-3 --train_attacker_projection_time_limit 5.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 3 --affix "low_cbf_reg_weight_1_seed_3" --gpu 1 &> low_cbf_reg_weight_1_seed_3.out &

nohup python main.py --phi_design "low" --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 1.0 --objective_option "weighted_average" --trainer_lr 1e-2 --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker_lr 1e-4 --train_attacker_projection_lr 1e-3 --train_attacker_projection_time_limit 5.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 4 --affix "low_cbf_reg_weight_1_seed_4" --gpu 1 &> low_cbf_reg_weight_1_seed_4.out &

nohup python main.py --phi_design "low" --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 1.0 --objective_option "weighted_average" --trainer_lr 1e-2 --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker_lr 1e-4 --train_attacker_projection_lr 1e-3 --train_attacker_projection_time_limit 5.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 5 --affix "low_cbf_reg_weight_1_seed_5" --gpu 2 &> low_cbf_reg_weight_1_seed_5.out &

nohup python main.py --phi_design "low" --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 1.0 --objective_option "weighted_average" --trainer_lr 1e-2 --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker_lr 1e-4 --train_attacker_projection_lr 1e-3 --train_attacker_projection_time_limit 5.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 6 --affix "low_cbf_reg_weight_1_seed_6" --gpu 2 &> low_cbf_reg_weight_1_seed_6.out &

nohup python main.py --phi_design "low" --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 1.0 --objective_option "weighted_average" --trainer_lr 1e-2 --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker_lr 1e-4 --train_attacker_projection_lr 1e-3 --train_attacker_projection_time_limit 5.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 7 --affix "low_cbf_reg_weight_1_seed_7" --gpu 3 &> low_cbf_reg_weight_1_seed_7.out &



