# The original
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 500 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --affix "ESG_reg_speedup_better_attacks_seed_0" --gpu 0 &> ESG_reg_speedup_better_attacks_seed_0.out &

# ON SERVER 4
# Varying regularization weights
# NEW LAUNCH
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 0.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_reg_weight_0" --gpu 0 &> best_reg_weight_0.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 10.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_reg_weight_10" --gpu 0 &> best_reg_weight_10.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 50.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_reg_weight_50" --gpu 0 &> best_reg_weight_50.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 200.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_reg_weight_200" --gpu 1 &> best_reg_weight_200.out &
#
## Varying p_reuse (proportion warmstarted)
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_p_reuse_0" --gpu 1 &> best_p_reuse_0.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.25 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_p_reuse_25" --gpu 2 &> best_p_reuse_25.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_p_reuse_50" --gpu 2 &> best_p_reuse_50.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.75 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_p_reuse_75" --gpu 3 &> best_p_reuse_75.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 100 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 1.0 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --trainer_n_steps 1500 --affix "best_p_reuse_100" --gpu 3 &> best_p_reuse_100.out &

# Varying size of batch

# ON SERVER 5! UNLIKE THE REST

#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 50 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --affix "best_critic_bs_50" --trainer_n_steps 1500 --gpu 0 &> best_critic_bs_50.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 150 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --affix "best_critic_bs_150" --trainer_n_steps 1500 --gpu 1 &> best_critic_bs_150.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 250 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --affix "best_critic_bs_250" --trainer_n_steps 1500 --gpu 2 &> best_critic_bs_250.out &
#
#nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 350 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker gradient_batch_warmstart_faster --gradient_batch_warmstart_faster_speedup_method sequential --gradient_batch_warmstart_faster_sampling_method gaussian --random_seed 0 --affix "best_critic_bs_350" --trainer_n_steps 1500 --gpu 3 &> best_critic_bs_350.out &






